const products = [
  {
    title: "Magnetite",
    category: 8,
    price: 89.0,
    img: "../assets/img/1.jpg",
    band: "Scalene",
    year: 2017,
    id: 0,
  },
  {
    title: "Acabou o Chorare",
    category: 2,
    price: 66.0,
    img: "../assets/img/2.jpg",
    band: "Novos Baianos",
    year: 1972,
    id: 1,
  },
  {
    title: "Nirvana Discografia",
    category: 8,
    price: 50.0,
    img: "../assets/img/3.jpg",
    band: "Nirvava",
    year: 1990,
    id: 2,
  },
  {
    title: "Both Sides",
    category: 8,
    price: 22.0,
    img: "../assets/img/4.jpg",
    band: "Phil Collins",
    year: 1993,
    id: 3,
  },
  {
    title: "Forró E Frevo",
    category: 3,
    price: 100.0,
    img: "../assets/img/sivuca.jpg",
    band: "Sivuca",
    year: 1980,
    id: 4,
  },
  {
    title: "My Beautiful Dark Twisted Fantasy",
    category: 6,
    price: 55.0,
    img: "../assets/img/kanye.jpg",
    band: "Kanye West",
    year: 2010,
    id: 5,
  },
];

const categories = [
  "Todos",
  "Pop",
  "MPB",
  "Forró",
  "Samba",
  "Baião",
  "Rap",
  "Hip-Hop",
  "Rock",
  "Reggae",
  "Country",
  "Gospel",
];
